name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install Dependencies
      run: go mod download

    - name: Format Check
      run: test -z "$(gofmt -l .)"

    - name: Vet
      run: go vet ./...

    - name: Unit Tests
      run: go test ./... -v

    - name: Build
      run: go build ./...
